#!/bin/bash

if [ $# -ne 2 ]
then
	echo "usage: reg_init <user1> <user2>"
	exit 1
fi

reg_create_user 60000 $1
reg_create_user 1 admin
reg_create_user 50000 $2
reg_create_theme battleship $1
reg_create_theme tictactoe $1


